In [2]:
import pandas as pd

In [27]:
# importing libraries
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score
from sklearn.preprocessing import StandardScaler

In [28]:
# data sourcing (data sourced from different schools of 10th passed out students)
df = pd.read_csv(r"C:\Users\badya\Downloads\10th result Project.csv")

In [29]:
df.head()

,Roll No,Punjabi,English,Hindi,Maths,Science,Social Science,Computer Science
0,1024251851,125,83,85,80,87,76,82
1,1024251852,128,88,88,79,82,71,87
2,1024251853,105,75,90,84,64,62,87
3,1024251854,131,89,87,87,88,80,88
4,1024251855,72,52,61,56,50,53,73

In [30]:
df.isnull().sum()

Roll No             0
Punjabi             0
English             0
Hindi               0
Maths               0
Science             0
Social Science      0
Computer Science    0
dtype: int64

In [31]:
def recommend_stream(row):
    maths = row['Maths']
    science = row['Science']
    english = row['English']
    
    avg = (maths + science + english) / 3

    if science >= 80 and maths >= 85:
        return 'Science (Non-Medical)'
    
    elif science >= 80 and english >= 70:
        return 'Science (Medical)'
    
    elif maths >= 60:
        return 'Commerce'
    
    else:
        return 'Arts'


df['Recommended_Stream'] = df.apply(recommend_stream, axis=1)

In [32]:
df

,Roll No,Punjabi,English,Hindi,Maths,Science,Social Science,Computer Science,Recommended_Stream
0,1024251851,125,83,85,80,87,76,82,Science (Medical)
1,1024251852,128,88,88,79,82,71,87,Science (Medical)
2,1024251853,105,75,90,84,64,62,87,Commerce
3,1024251854,131,89,87,87,88,80,88,Science (Non-Medical)
4,1024251855,72,52,61,56,50,53,73,Arts
...,...,...,...,...,...,...,...,...,...
132,1025252802,108,20,98,67,20,98,67,Commerce
133,1025252803,106,66,83,34,82,82,45,Arts
134,1025252804,108,20,98,67,20,98,67,Commerce
135,1025252805,128,98,67,20,98,67,20,Science (Medical)
136,1025252806,106,66,83,34,82,82,45,Arts

In [33]:
df.shape

(137, 9)

In [34]:
df['Recommended_Stream'] = df['Recommended_Stream'].map({'Science (Medical)': 0, 'Science (Non-Medical)': 1, 'Commerce':2, 'Arts':3})

In [35]:
x = df[['Science','English','Maths']]

In [36]:
y = df['Recommended_Stream']

In [37]:
y.isnull().sum()

0

In [38]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [39]:
scaler = StandardScaler()

In [40]:
x_train_scaled = scaler.fit_transform(x_train)

In [41]:
x_test_scaled = scaler.transform(x_test)

In [42]:
model = RandomForestRegressor(n_estimators=100, max_depth=4, random_state=42)

In [43]:
model.fit(x_train_scaled,y_train)

RandomForestRegressor(max_depth=4, random_state=42)

In [44]:
# prediction on test data
y_pred = model.predict(x_test_scaled)

In [45]:
r2_score(y_test,y_pred)

0.9561910112359551

In [46]:
# prediction on training data
x_pred = model.predict(x_train_scaled)

In [47]:
r2_score(y_train,x_pred)

0.9934898745385199

In [48]:
df.head()

,Roll No,Punjabi,English,Hindi,Maths,Science,Social Science,Computer Science,Recommended_Stream
0,1024251851,125,83,85,80,87,76,82,0
1,1024251852,128,88,88,79,82,71,87,0
2,1024251853,105,75,90,84,64,62,87,2
3,1024251854,131,89,87,87,88,80,88,1
4,1024251855,72,52,61,56,50,53,73,3

In [49]:
df['Recommended_Stream'].value_counts()

2    61
3    36
0    23
1    17
Name: Recommended_Stream, dtype: int64

In [50]:
new = [[96, 80, 66]]
new_scaled = scaler.transform(new)
model.predict(new_scaled)

C:\Users\badya\AppData\Roaming\Python\Python38\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

array([0.02])